FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake libboost-all-dev libssl-dev

COPY . /repo
WORKDIR /repo/build
RUN cmake .. -DBUILD_TESTING=0 -DBUILD_EXAMPLES=1 -DBUILD_THREAD=1
RUN make -j8
